apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-kafka
  namespace: javapro-team33
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 30035
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_HEAP_OPTS
              value: -Xms320m
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service.javapro-team33:2181
