spring:
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

 liquibase:
    enabled: true
    drop-first: ${SWITCH_DROP_FIRST}
    change-log: classpath:db/db-changelog-master.xml
    default-schema: public

 jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: public
jwt:
  secret:
    access: jwtsocialserviceapptywrtywryhwsrtyhsfthshsrhsrth
    refresh: jwtsocialsirviceapprefreshtokenstrhsrthhtrstthsrhsh

whitelist:
  permit:
    - /**/login
    - /**/captcha
    - /**/register
    - /**/registration
    - /**/v3/api-docs/**
    - /**/swagger-ui/**