spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 13asapum



  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/db-changelog-master.xml
    default-schema: public

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: public

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      group-id: testLocal

topic:
  name: social-service-topic

jwt:
  secret:
    access: jwtsocialserviceapptywrtywryhwsrtyhsfthshsrhsrth
    refresh: jwtsocialsirviceapprefreshtokenstrhsrthhtrstthsrhsh

whitelist:
  permit:
    - /**/login
    - /**/captcha
    - /**/register
    - /**/registration
    - /**/v3/api-docs/**
    - /**/swagger-ui/**