apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: social-service-ingress
  namespace: javapro-team33
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: backend-service
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: social-service
                port:
                  number: 8080